# Source set pages by path ("{set slug}/{id}") => item, hub, contributor, title.
# Built by ingestion3's scripts/pss_sources.py. PssEvents uses it to
# attribute page views, since the GA4 events lack hub and item.
class PssSources
  extend SThreeJsonMap

  KEY = "hub-stats/pss_sources.json"

  # Regenerated by hand, so no staleness alert.
  s3_json_map KEY, "sources", stale_after: nil

  # Entries for items no longer in the index have no "hub".
  def self.sources
    entries
  end

  # Drives the sidebar link. Same data as the table, so they agree.
  def self.participant?(hub, contributor = nil)
    sources.any? { |_path, entry| held_by?(entry, hub, contributor) }
  end

  def self.held_by?(entry, hub, contributor = nil)
    hub.present? && entry.is_a?(Hash) && entry["hub"] == hub &&
      (contributor.nil? || entry["contributor"] == contributor)
  end
end
